
package interfacez;

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import laboratorio_clinico.conexion_MYSQL;

public class user extends javax.swing.JFrame {

        // Esrtablecer conexion a MYSQL
        conexion_MYSQL c = new conexion_MYSQL();
        Connection conectar = c.obtener_conexion();

        public user() {
                initComponents();
                this.setLocationRelativeTo(null);
                Image icon = new ImageIcon(getClass().getResource("/images/icon.png")).getImage();
                setIconImage(icon);

                btn_update.setEnabled(false);
                btn_delete.setEnabled(false);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                txt_codU = new javax.swing.JTextField();
                txt_nameU = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                txt_nameUU = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                txt_lastnameU = new javax.swing.JTextField();
                combo_cargoU = new javax.swing.JComboBox<>();
                jLabel12 = new javax.swing.JLabel();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                passwU1 = new javax.swing.JPasswordField();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                txt_cod = new javax.swing.JTextField();
                txt_nomU = new javax.swing.JTextField();
                txt_name = new javax.swing.JTextField();
                txt_lastname = new javax.swing.JTextField();
                combo_cargo = new javax.swing.JComboBox<>();
                jButton2 = new javax.swing.JButton();
                btn_delete = new javax.swing.JButton();
                btn_update = new javax.swing.JButton();
                jButton7 = new javax.swing.JButton();
                passwU = new javax.swing.JPasswordField();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setUndecorated(true);

                jPanel1.setBackground(new java.awt.Color(250, 240, 212));
                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios",
                                javax.swing.border.TitledBorder.CENTER,
                                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                                new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

                jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jTabbedPane1KeyPressed(evt);
                        }
                });

                jPanel2.setBackground(new java.awt.Color(204, 204, 254));

                jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(0, 0, 0));
                jLabel7.setText("Cod:");

                txt_codU.setBackground(new java.awt.Color(255, 255, 255));
                txt_codU.setForeground(new java.awt.Color(0, 0, 0));

                txt_nameU.setBackground(new java.awt.Color(255, 255, 255));
                txt_nameU.setForeground(new java.awt.Color(0, 0, 0));

                jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(0, 0, 0));
                jLabel8.setText("Nombre Usuario");

                jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(0, 0, 0));
                jLabel9.setText("Contraseña");

                txt_nameUU.setBackground(new java.awt.Color(255, 255, 255));
                txt_nameUU.setForeground(new java.awt.Color(0, 0, 0));

                jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(0, 0, 0));
                jLabel10.setText("Nombre:");

                jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(0, 0, 0));
                jLabel11.setText("Apellido:");

                txt_lastnameU.setBackground(new java.awt.Color(255, 255, 255));
                txt_lastnameU.setForeground(new java.awt.Color(0, 0, 0));

                combo_cargoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador" }));

                jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(0, 0, 0));
                jLabel12.setText("Cargo");

                jButton4.setBackground(new java.awt.Color(255, 255, 255));
                jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jButton4.setForeground(new java.awt.Color(0, 0, 0));
                jButton4.setText("Cancelar");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jButton5.setBackground(new java.awt.Color(255, 255, 255));
                jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jButton5.setForeground(new java.awt.Color(0, 0, 0));
                jButton5.setText("Guardar");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                passwU1.setBackground(new java.awt.Color(255, 255, 255));
                passwU1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
                passwU1.setForeground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel8)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(jLabel7))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txt_codU,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                80,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jButton5)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jButton4))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(txt_nameUU,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                184,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(txt_nameU,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                184,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(txt_lastnameU,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                184,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(combo_cargoU,
                                                                                                                0,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(passwU1,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)))
                                                                .addContainerGap(32, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addComponent(txt_codU,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel8)
                                                                                                                .addComponent(txt_nameU,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jLabel9)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jLabel10)
                                                                                                .addGap(6, 6, 6))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(passwU1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(txt_nameUU,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txt_lastnameU,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel11))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(combo_cargoU,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 25, Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton5)
                                                                                .addComponent(jButton4))
                                                                .addGap(15, 15, 15)));

                jTabbedPane1.addTab("Nuevo Usuario", jPanel2);

                jPanel4.setBackground(new java.awt.Color(204, 255, 204));

                jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 0, 0));
                jLabel1.setText("Cod:");

                jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 0, 0));
                jLabel2.setText("Nombre Usuario");

                jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(0, 0, 0));
                jLabel3.setText("Contraseña");

                jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(0, 0, 0));
                jLabel4.setText("Nombre:");

                jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(0, 0, 0));
                jLabel5.setText("Apellido:");

                jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(0, 0, 0));
                jLabel6.setText("Cargo");

                txt_cod.setBackground(new java.awt.Color(255, 255, 255));
                txt_cod.setForeground(new java.awt.Color(0, 0, 0));

                txt_nomU.setBackground(new java.awt.Color(255, 255, 255));
                txt_nomU.setForeground(new java.awt.Color(0, 0, 0));

                txt_name.setBackground(new java.awt.Color(255, 255, 255));
                txt_name.setForeground(new java.awt.Color(0, 0, 0));

                txt_lastname.setBackground(new java.awt.Color(255, 255, 255));
                txt_lastname.setForeground(new java.awt.Color(0, 0, 0));
                txt_lastname.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_lastnameActionPerformed(evt);
                        }
                });

                combo_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador" }));

                jButton2.setBackground(new java.awt.Color(255, 255, 255));
                jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jButton2.setForeground(new java.awt.Color(0, 0, 0));
                jButton2.setText("Cancelar");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                btn_delete.setBackground(new java.awt.Color(255, 255, 255));
                btn_delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                btn_delete.setForeground(new java.awt.Color(0, 0, 0));
                btn_delete.setText("Eliminar");
                btn_delete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_deleteActionPerformed(evt);
                        }
                });

                btn_update.setBackground(new java.awt.Color(255, 255, 255));
                btn_update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                btn_update.setForeground(new java.awt.Color(0, 0, 0));
                btn_update.setText("Actualizar");
                btn_update.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_updateActionPerformed(evt);
                        }
                });

                jButton7.setBackground(new java.awt.Color(255, 255, 255));
                jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jButton7.setForeground(new java.awt.Color(0, 0, 0));
                jButton7.setText("Mi Usuario");
                jButton7.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton7ActionPerformed(evt);
                        }
                });

                passwU.setBackground(new java.awt.Color(255, 255, 255));
                passwU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
                passwU.setForeground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(btn_update))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(btn_delete)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jButton2))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                false)
                                                                                                .addComponent(passwU,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(txt_cod,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                68,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jButton7))
                                                                                                .addComponent(txt_name,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                184,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(txt_nomU,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                184,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(txt_lastname,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                184,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(combo_cargo,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                0,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap(39, Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addComponent(txt_cod,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButton7))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(txt_nomU,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(passwU,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel4))
                                                                                .addComponent(txt_name,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(txt_lastname,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(combo_cargo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(btn_delete)
                                                                                                .addComponent(jButton2))
                                                                                .addComponent(btn_update))
                                                                .addContainerGap(13, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                jTabbedPane1.addTab("Mi Usuario", jPanel3);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTabbedPane1));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jTabbedPane1)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                dispose();
        }// GEN-LAST:event_jButton2ActionPerformed

        private void txt_lastnameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_lastnameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_lastnameActionPerformed

        private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_deleteActionPerformed
                try {
                        // Preparacion de un Query para eliminar datos
                        PreparedStatement pps = conectar
                                        .prepareStatement("DELETE FROM usuarios WHERE cod_usuario='" + txt_cod.getText()
                                                        + "'");
                        // ejecutamos query
                        pps.execute();
                        // Mensaje
                        JOptionPane.showMessageDialog(null, "Usuario eliminado");
                        this.dispose();

                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Error al eliminar Usuario.\n" + e);
                }
        }// GEN-LAST:event_btn_deleteActionPerformed

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
                dispose();
        }// GEN-LAST:event_jButton4ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
                try {
                        // llamado del stored procedures de MYSQL
                        CallableStatement insert = conectar.prepareCall("{call new_user(?,?,?,?,?,?)}"); // ta
                        insert.setString(1, txt_codU.getText()); // ta
                        insert.setString(2, txt_nameU.getText()); // ta
                        insert.setString(3, passwU1.getText()); // ta
                        insert.setString(4, txt_nameUU.getText()); // ta
                        insert.setString(5, txt_lastnameU.getText()); // ta
                        insert.setString(6, combo_cargoU.getSelectedItem().toString()); // ta
                        // ejecutamos query
                        insert.execute();
                        // presentamos mensaje de registro
                        JOptionPane.showMessageDialog(null, "Usuario Agregado");
                        this.dispose();

                } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e);
                }
        }// GEN-LAST:event_jButton5ActionPerformed

        /*
         * Coste tiempo
         * T= ta + ta + ta + ta + ta +ta + ta
         * T= 7ta
         */

        private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_updateActionPerformed
                try {
                        // llamado del stored procedures de MYSQL
                        CallableStatement update = conectar.prepareCall("{call update_user(?,?,?,?,?,?)}"); // ta
                        update.setString(1, txt_cod.getText()); // ta
                        update.setString(2, txt_nomU.getText()); // ta
                        update.setString(3, passwU.getText()); // ta
                        update.setString(4, txt_name.getText()); // ta
                        update.setString(5, txt_lastname.getText()); // ta
                        update.setString(6, combo_cargo.getSelectedItem().toString());
                        // ejecutamos query
                        update.execute();
                        // presentamos mensaje de registro
                        JOptionPane.showMessageDialog(null, "Usuario Actualizado");
                        this.dispose();

                } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e);
                }
        }// GEN-LAST:event_btn_updateActionPerformed

        /*
         * Coste tiempo
         * T= ta + ta + ta + ta + ta +ta
         * T= 6ta
         */
        private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTabbedPane1KeyPressed
                JOptionPane.showMessageDialog(null, "hola");
        }// GEN-LAST:event_jTabbedPane1KeyPressed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed

                String user = JOptionPane.showInputDialog(null, "Usuario"); // ta
                String passw = JOptionPane.showInputDialog(null, "Contrasena"); // ta

                int resultado = 1; // ta
                // Query para seleciconar un usuario a la base de datos
                String sql = "SELECT * FROM usuarios WHERE nom_usuario='" + user + "'AND contraseña='" + passw + "'"; // ta
                try {
                        // creamos un aconexion a la base de datos
                        Statement st = conectar.createStatement(); // ta
                        ResultSet rs = st.executeQuery(sql); // ta
                        if (rs.next()) { // tc

                                if (resultado == 1) { // (tc*1)+tc
                                        txt_cod.setText(rs.getString("cod_usuario")); // ta
                                        txt_nomU.setText(rs.getString("nom_usuario")); // ta
                                        passwU.setText(rs.getString("contraseña")); // ta
                                        txt_name.setText(rs.getString("nombres")); // ta
                                        txt_lastname.setText(rs.getString("apellidos")); // ta
                                        combo_cargo.setSelectedItem(rs.getString("cargo")); // ta
                                        btn_update.setEnabled(true);
                                        btn_delete.setEnabled(true);
                                }
                        } else {
                                JOptionPane.showMessageDialog(null,
                                                "Usuario y/o contraseña no son correctos \n Intente nuevamente.");
                        }
                } catch (HeadlessException | SQLException e) {
                        System.out.println(e);
                }

        }// GEN-LAST:event_jButton7ActionPerformed
        /*
         * T = ta +ta + ta+ ta + ta +ta +tc + tc + ta + ta + ta + ta +ta +ta
         * T= 12ta + 2tc
         */

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) { // (to
                                                                       // +
                                                                       // tc)
                                if ("Nimbus".equals(info.getName())) { // tc + tc
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new user().setVisible(true);
                        }
                });
        }

        /*
         * T= TO +TC + TC + TC
         * T = to +3
         * T= TO +3
         */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_delete;
        private javax.swing.JButton btn_update;
        private javax.swing.JComboBox<String> combo_cargo;
        private javax.swing.JComboBox<String> combo_cargoU;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton7;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JPasswordField passwU;
        private javax.swing.JPasswordField passwU1;
        private static javax.swing.JTextField txt_cod;
        public static javax.swing.JTextField txt_codU;
        private javax.swing.JTextField txt_lastname;
        public static javax.swing.JTextField txt_lastnameU;
        private javax.swing.JTextField txt_name;
        public static javax.swing.JTextField txt_nameU;
        public static javax.swing.JTextField txt_nameUU;
        private javax.swing.JTextField txt_nomU;
        // End of variables declaration//GEN-END:variables
}
